GET http://localhost:1234/api/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTcwNjMwMDc4MCwiZXhwIjoxNzA2MzA0MzgwfQ.B2APl18xGxmStgYMmXwLRdMj9F5M65k8RN4yiqKR9lw